flask:
    DEBUG: true
    SERVER_NAME: localhost:81
db:
    drivername: mysql+mysqlconnector
    host: localhost
    port: 3306
    username: root
    password: root123
    database: chiasma
#db1:
#    host: quezixiong.mysql.rds.aliyuncs.com
#    user: quezixiong
#    passwd: quezixiong
#    db: ipdatabase
